export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_PUBLIC_REQUEST = 'CHANGE_PUBLIC_REQUEST';
export const CHANGE_PUBLIC_SUCCESS = 'CHANGE_PUBLIC_SUCCESS';
export const CHANGE_PUBLIC_FAILURE = 'CHANGE_PUBLIC_FAILURE';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const PROFILE_FAILURE = 'PROFILE_FAILURE';
