const types = {
  AUTH_RESPONSE            : 'AUTH_RESPONSE',
  CHANGE_PASSWORD_RESPONSE : 'CHANGE_PASSWORD_RESPONSE',
  CHANGE_PUBLIC_RESPONSE   : 'CHANGE_PUBLIC_RESPONSE',
  IS_AUTHENTICATED         : 'IS_AUTHENTICATED',
  IS_ONLINE                : 'IS_ONLINE',
  LOGOUT_USER              : 'LOGOUT_USER',
  PROFILE_RESPONSE         : 'PROFILE_RESPONSE',
  SAY_HELLO_RESPONSE       : 'SAY_HELLO_RESPONSE',
  TOGGLE_IN_PROGRESS       : 'TOGGLE_IN_PROGRESS',
  TOGGLE_KEY               : 'TOGGLE_KEY',
  TOGGLE_SIDEBAR           : 'TOGGLE_SIDEBAR',
};

export default types;
